config/routes.rb
Rails.application.routes.draw do
  resources :assemblies
  resources :parts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/assembly.rb
class Assembly < ApplicationRecord
  has_and_belongs_to_many :parts
end

app/models/part.rb
class Part < ApplicationRecord
  has_and_belongs_to_many :assemblies
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/assemblies_controller.rb
class AssembliesController < ApplicationController
  before_action :set_assembly, only: [:show, :edit, :update, :destroy]
  before_action :set_parts, only: [:new, :create, :edit, :update]

  # GET /assemblies
  # GET /assemblies.json
  def index
    @assemblies = Assembly.all
  end

  # GET /assemblies/1
  # GET /assemblies/1.json
  def show
  end

  # GET /assemblies/new
  def new
    @assembly = Assembly.new
  end

  # GET /assemblies/1/edit
  def edit
  end

  # POST /assemblies
  # POST /assemblies.json
  def create
    @assembly = Assembly.new(assembly_params)

    respond_to do |format|
      if @assembly.save
        @assembly.parts << Part.where(id: params[:parts])
        format.html { redirect_to @assembly, notice: 'Assembly was successfully created.' }
        format.json { render :show, status: :created, location: @assembly }
      else
        format.html { render :new }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /assemblies/1
  # PATCH/PUT /assemblies/1.json
  def update
    respond_to do |format|
      if @assembly.update(assembly_params)
        existing_ids = @assembly.parts.where(id: params[:parts]).pluck(:id).uniq
        new_id = params[:parts].map(&:to_i) - existing_ids
        @assembly.parts << Part.where(id: new_id) if new_id.present?
        format.html { redirect_to @assembly, notice: 'Assembly was successfully updated.' }
        format.json { render :show, status: :ok, location: @assembly }
      else
        format.html { render :edit }
        format.json { render json: @assembly.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assemblies/1
  # DELETE /assemblies/1.json
  def destroy
    @assembly.destroy
    respond_to do |format|
      format.html { redirect_to assemblies_url, notice: 'Assembly was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_assembly
      @assembly = Assembly.find(params[:id])
    end

    def set_parts
      @parts = Part.pluck(:part_number,:id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def assembly_params
      params.require(:assembly).permit(:name)
    end
end

app/controllers/parts_controller.rb
class PartsController < ApplicationController
  before_action :set_part, only: [:show, :edit, :update, :destroy]

  # GET /parts
  # GET /parts.json
  def index
    @parts = Part.all
  end

  # GET /parts/1
  # GET /parts/1.json
  def show
  end

  # GET /parts/new
  def new
    @part = Part.new
  end

  # GET /parts/1/edit
  def edit
  end

  # POST /parts
  # POST /parts.json
  def create
    @part = Part.new(part_params)

    respond_to do |format|
      if @part.save
        format.html { redirect_to @part, notice: 'Part was successfully created.' }
        format.json { render :show, status: :created, location: @part }
      else
        format.html { render :new }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /parts/1
  # PATCH/PUT /parts/1.json
  def update
    respond_to do |format|
      if @part.update(part_params)
        format.html { redirect_to @part, notice: 'Part was successfully updated.' }
        format.json { render :show, status: :ok, location: @part }
      else
        format.html { render :edit }
        format.json { render json: @part.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /parts/1
  # DELETE /parts/1.json
  def destroy
    @part.destroy
    respond_to do |format|
      format.html { redirect_to parts_url, notice: 'Part was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_part
      @part = Part.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def part_params
      params.require(:part).permit(:part_number)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/assemblies_helper.rb
module AssembliesHelper
end

app/helpers/parts_helper.rb
module PartsHelper
end

app/views/assemblies/_form.html.erb
<%= form_with(model: assembly, local: true) do |form| %>
  <% if assembly.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(assembly.errors.count, "error") %> prohibited this assembly from being saved:</h2>

      <ul>
        <% assembly.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div class="field">
    <%= form.label :name %>
    <%= select_tag "parts[]", options_for_select(@parts), {:multiple => true} %>
  </div>

  <%#= form.select 'parts[]', options_for_select(@parts.map { |s| [s.part_number, s.id] }), multiple: true, size: 10 %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/assemblies/edit.html.erb
<h1>Editing Assembly</h1>

<%= render 'form', assembly: @assembly %>

<%= link_to 'Show', @assembly %> |
<%= link_to 'Back', assemblies_path %>

app/views/assemblies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Assemblies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @assemblies.each do |assembly| %>
      <tr>
        <td><%= assembly.name %></td>
        <td><%= link_to 'Show', assembly %></td>
        <td><%= link_to 'Edit', edit_assembly_path(assembly) %></td>
        <td><%= link_to 'Destroy', assembly, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Assembly', new_assembly_path %>

app/views/assemblies/new.html.erb
<h1>New Assembly</h1>

<%= render 'form', assembly: @assembly %>

<%= link_to 'Back', assemblies_path %>

app/views/assemblies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @assembly.name %>
</p>

<h1>Part number</h1>
<% @assembly.parts.each do |part| %>
<p><%= part.part_number %></p>
<% end %>

<%= link_to 'Edit', edit_assembly_path(@assembly) %> |
<%= link_to 'Back', assemblies_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AssemblyPartApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/parts/_form.html.erb
<%= form_with(model: part, local: true) do |form| %>
  <% if part.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(part.errors.count, "error") %> prohibited this part from being saved:</h2>

      <ul>
        <% part.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :part_number %>
    <%= form.text_field :part_number %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/parts/edit.html.erb
<h1>Editing Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Show', @part %> |
<%= link_to 'Back', parts_path %>

app/views/parts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Parts</h1>

<table>
  <thead>
    <tr>
      <th>Part number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @parts.each do |part| %>
      <tr>
        <td><%= part.part_number %></td>
        <td><%= link_to 'Show', part %></td>
        <td><%= link_to 'Edit', edit_part_path(part) %></td>
        <td><%= link_to 'Destroy', part, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Part', new_part_path %>

app/views/parts/new.html.erb
<h1>New Part</h1>

<%= render 'form', part: @part %>

<%= link_to 'Back', parts_path %>

app/views/parts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Part number:</strong>
  <%= @part.part_number %>
</p>

<%= link_to 'Edit', edit_part_path(@part) %> |
<%= link_to 'Back', parts_path %>